version: '{branch}-{build}'

configuration: Release

before_build:
  - nuget restore

build:
  verbosity: minimal

artifacts:
  - path: 'Namespace Tree Folder Editor\bin\$(configuration)\*'
    name: NamespaceTreeFolderEditor
    type: zip