version: '{branch}-{build}'

configuration: Release

before_build:
  - nuget restore

build:
  verbosity: minimal

after_build:
  - 7z a "NamespaceTreeFolderEditor.zip" "%APPVEYOR_BUILD_FOLDER%\Namespace Tree Folder Editor\bin\%configuration%\*.*"

artifacts:
  - path: 'NamespaceTreeFolderEditor.zip'